<?php

return [
    'base_url' => env('MOVACAL_BASE_URL', 'https://link.movacal.net/service/api/v1'),

    'basic' => [
        'id' => env('MOVACAL_BASIC_ID', ''),
        'password' => env('MOVACAL_BASIC_PASSWORD', ''),
    ],

    // credential 認証用
    'provider' => env('MOVACAL_PROVIDER', ''),
    'secret_key' => env('MOVACAL_SECRET_KEY', ''),

    // credential キャッシュ秒数（デフォルト: 15分 = 900秒）
    'credential_ttl' => (int) env('MOVACAL_CREDENTIAL_TTL', 900),

    'default_params_json' => env('MOVACAL_DEFAULT_PARAMS_JSON', '{}'),

    'allowed_endpoints' => [
        'credential.php',
        'postMemo.php',
        'getPatientlist.php',
        'postPatient.php',
        'getPatient.php',
        'getPatient2.php',
        'getDiaglist.php',
        'postDiag.php',
        'getDiagdata.php',
        'getDiagAttachement.php',
        'getExamlist.php',
        'getExamdata.php',
        'getDocslist.php',
        'getDocsdata.php',
        'getDispdocs.php',
        'getDocsmap.php',
        'postSchedule.php',
        'deleteSchedule.php',
        'getSchedule.php',
        'postFacility.php',
        'getFacility.php',
        'postDisease.php',
        'getDisease.php',
        'postRoutinePres.php',
        'getVisitNurse.php',
        'postBoardMessage.php',
        'deleteBoardMessage.php',
        'updateMSRelation.php',
        'getUserData.php',
        'postActcode.php',
        'getActcode.php',
        'getReserve.php',
        'getSummaryItem.php',
        'getHospitalization.php',
        'postHospitalization.php',
        'postVitalData.php',
        'deleteVitalData.php',
        'postReserve.php',
        'changeReserve.php',
        'getOuterChecked.php',
        'checkReserve.php',
        'getVersion.php',
        'postDiagObjective.php',
        'getNursePeriod.php',
        'getFilelist.php',
        'getFile.php',
        'getFileCategory.php',
        'getNrecorddata.php',
        'getNrecordAttachment.php',
        'postDocFile.php',
        'getPatientHistory.php',
        'getBasicOrder.php',
    ],
];
